name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would it solve?
      description: Describe the situation, not only the solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
  - type: checkboxes
    id: help
    attributes:
      label: Contributing
      options:
        - label: I'd like to work on this
